version: '2'

services:
  elasticsearch:
    build: ./elasticsearch/image
    container_name: 'elasticsearch'
    restart: unless-stopped
  mysql:
    image: mysql:5.7.30
    ports:
      - 3306:3306
    container_name: 'mysql'
    restart: unless-stopped
