version: '2'

services:
  es:
    build: ./elasticsearch/image/
    container_name: 'super.elasticsearch'
    ports:
      - 9200
      - 9300
    environment:
      - discovery.type=single-node
    restart: always
  db:
    image: mysql:5.7.30
    ports:
      - 3306
    container_name: 'super.mysql'
    command:  --character-set-server=utf8 --default-timezone=+8:00 --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
  db-admin:
    image: adminer
    container_name: 'super.mysql-admin'
    restart: always
    ports:
      - 8080
